// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATwwDEz_gpLBC5V4W79Dx47ITYVcAJdAU',
    appId: '1:225774294562:web:3967efabe82654985a9c7b',
    messagingSenderId: '225774294562',
    projectId: 'project-1-29d9c',
    authDomain: 'project-1-29d9c.firebaseapp.com',
    storageBucket: 'project-1-29d9c.appspot.com',
    measurementId: 'G-T5PZ189KYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAVOAHPR46IPl2HQWBb3ekeI0561QYuzM',
    appId: '1:225774294562:android:0157a4ab264b79355a9c7b',
    messagingSenderId: '225774294562',
    projectId: 'project-1-29d9c',
    storageBucket: 'project-1-29d9c.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHscKh1YchEcn7_yzo5u71C1yXH8olNWI',
    appId: '1:225774294562:ios:d851ef138cbf739b5a9c7b',
    messagingSenderId: '225774294562',
    projectId: 'project-1-29d9c',
    storageBucket: 'project-1-29d9c.appspot.com',
    iosBundleId: 'com.example.authBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATwwDEz_gpLBC5V4W79Dx47ITYVcAJdAU',
    appId: '1:225774294562:web:376b04e5a4b8281d5a9c7b',
    messagingSenderId: '225774294562',
    projectId: 'project-1-29d9c',
    authDomain: 'project-1-29d9c.firebaseapp.com',
    storageBucket: 'project-1-29d9c.appspot.com',
    measurementId: 'G-MJZWQHCEKF',
  );
}
